version: "3.9"

services:
  server:
    environment:
      - NODE_ENV=prod
    build:
      dockerfile: server/Dockerfile
      context: ./
    ports:
      - 8000:8000
#   db:
#     image: postgres:14.1-alpine
#     restart: always
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=${PG_DB}
#       - POSTGRES_USER=${PG_USER}
#       - POSTGRES_PASSWORD=${PG_PASSWORD}
#     ports:
#       - "5432:5432"

# volumes:
#   pgdata:
